import type { ErrorCode, ErrorStatusCode } from '../types/index.js';

export const ERROR_CODE_KEYS = {
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  DATABASE_ERROR: 'DATABASE_ERROR',
} as const;

export const STATUS_BY_ERROR_CODE: Record<ErrorCode, ErrorStatusCode> = {
  [ERROR_CODE_KEYS.BAD_REQUEST]: 400,
  [ERROR_CODE_KEYS.UNAUTHORIZED]: 401,
  [ERROR_CODE_KEYS.FORBIDDEN]: 403,
  [ERROR_CODE_KEYS.NOT_FOUND]: 404,
  [ERROR_CODE_KEYS.CONFLICT]: 409,
  [ERROR_CODE_KEYS.INTERNAL_ERROR]: 500,
  [ERROR_CODE_KEYS.VALIDATION_ERROR]: 400,
  [ERROR_CODE_KEYS.DATABASE_ERROR]: 500,
};

export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODE_KEYS.BAD_REQUEST]: 'Bad request',
  [ERROR_CODE_KEYS.UNAUTHORIZED]: 'Unauthorized',
  [ERROR_CODE_KEYS.FORBIDDEN]: 'Forbidden',
  [ERROR_CODE_KEYS.NOT_FOUND]: 'Resource not found',
  [ERROR_CODE_KEYS.CONFLICT]: 'Resource already exists',
  [ERROR_CODE_KEYS.INTERNAL_ERROR]: 'Internal server error',
  [ERROR_CODE_KEYS.VALIDATION_ERROR]: 'Validation failed',
  [ERROR_CODE_KEYS.DATABASE_ERROR]: 'Database error',
};
